# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8hbgfO3yg6WZWJdfOn1WmMXRqKy62Tz
"""

name="NLP Lap"
hours=30
pi=3.0
topics=["tokenziation","POS tagging", "NER"]


if hours > 25:
    print("sufficient hours for learning python.")
else:
    print("Add more practice hourse.")

for topic in  topics:
    print("Learning:", topic)


def greet(student_name):
    return "Welcome to"+student_name

print(greet("AI & NLP Lab"))